### ISSUE TITLE
In mac, reconnect loop with 'Invalid state error'

### ISSUE THREAD

**Issue by Latchumi** [cayasso/primus.io#14]
When the network goes down and comes, the primus reconnect happens. But it is getting triggered in loop. Also it shows the "INVALID_STATE_ERR" and also, 'websocket is closed before the connection is established'.  I am using Primus with sockJS for transports.

**Note**: On reconnect, I am removing(ending) the existing socket connection and want to make new socket connection with certain condition for my client session validation.

Works fine in windows machine. Only in mac this reconnect in loop is happening. Can some one suggest what the issue is?

**Comment by cayasso** [comment]
Do to no response, I am closing this.
