### ISSUE TITLE
Version not update in npm repository

### ISSUE THREAD

**Issue by arvind-agarwal** [cayasso/primus.io#20]
The package.json file points to primus - 2.4.x in npm repository, although your github repository show it as 3.1.x, the npm repository seems out of sync of your github. 

Requesting update of npm repository.

**Comment by cayasso** [comment]
Hey @arvind-agarwal primus.io@3.2.0 is out :)

**Comment by arvind-agarwal** [comment]
@cayasso I still see old version in npm https://www.npmjs.com/package/primus.io

**Comment by arvind-agarwal** [comment]
I see it is updated in npm now, thanks
