### ISSUE TITLE
Sometimes primus-rooms crushes when joining room after re-connect.

### ISSUE THREAD

**Issue by bfunc** [cayasso/primus.io#25]
primus-rooms crushes when joining room after re-connect.

1. the issue happens is when clients re-connecting (local developent with webpack page reload on code change)
2. it is happens when more that one client (opened tab) are re-connecting at same time (one tab works well)

```node_modules\primus-rooms\lib\index.js:171
      return this._rooms[fn].apply(this._rooms, arguments);
                        ^
TypeError: Cannot read property 'join' of undefined 
                  at Sparky.<anonymous> (...\node_modules\primus-rooms\lib\index.js:171:25)
```

**Comment by degecko** [comment]
@bfunc Did you manage to fix this issue? I've just hit it myself and I can't figure out what the problem is.

**Comment by bfunc** [comment]
May be it is not right, it is my personal opinion. The idea behind Primus is great, but currently websockets are implemented natively in browser and there is ws lib for node.js, that is almost native (15,000,000 weekly downloads). Seems like it is not going to change. Althought, I do need to write more code,  I choose not use Prius in current stack. By the way I do use [recovery](https://www.npmjs.com/package/recovery) to do perform reconnect logic.
